### ISSUE TITLE
No last location known and with bug report from MacOS Export Wizard

### ISSUE THREAD

**Issue by SadGare** [parawanderer/OpenTagViewer#33]
First when I ran MacOS Export Wizard, it immediately poped up 

Found an unexpected naming record at /Users/gare/Library/com.apple.icloud.searchpartyd/BeaconNamingRecord/61861A6A-404A-43B6-BAFB-5D3A310FDB94/08EC99F4-1239-43C3-AF24-C81EC054767F.record! 

Report this as a bug on Github: https://github.com/parawanderer/OpenTagViewer/issues/new

While I just ignored this and the exported the zip file as usual.

But when I import zip into phone app, it did show the devices. But no matter how long I wait, still no location info.

And I exported the log file of the phone app.

[OpenTagViewer-1757859137541.log.txt](https://github.com/user-attachments/files/22320807/OpenTagViewer-1757859137541.log.txt)

Thank for any fix or reply.

**Comment by parawanderer** [comment]
I think your root cause is this 

```

09-14 22:12:00.351 32289  7656 I python.stdout: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gsa.apple.com:443 ssl:False [None]
09-14 22:12:00.351 32289  7656 I python.stdout: 
09-14 22:12:00.351 32289  7656 E PythonAppleService: python call to getLastReports resulted in error (check python logs for details)
```

That's Apple's servers. The first thing I'd do is wait for a bit (a day?) and then log out and log back in again in the app (to do a clean Auth)

If you can't connect to the apple servers your authentication state is questionable and you most certainly would not be able to fetch any reports for your tags

Let me know if you find this automatically resolves for you or not (or if you get a new error)! It's possible there's just some issue on apple's side for any reason, which I imagine will likely be fixed by tomorrow if so.

**Comment by parawanderer** [comment]
Sidenote regarding your 1st error msg: could you let me know what the folder structure of your `/Users/gare/Library/com.apple.icloud.searchpartyd/` folder is? In particular I'm looking for an entry in another folder that matches to `61861A6A-404A-43B6-BAFB-5D3A310FDB94`

**Comment by SadGare** [comment]
I have done the log out and in operation in the phone app. And it seemed nothing happened. Still not working and no error. I will try this more in the future.

<img width="1261" height="1209" alt="Image" src="https://github.com/user-attachments/assets/7c939584-2ac1-4ddd-8f5a-2108555c79ea" />

And about the structure of the folder, there is only one folder named 61861A6A-404A-43B6-BAFB-5D3A310FDB94.

**Comment by parawanderer** [comment]
Hmmm okay, in that case try to use a different Anisette server? Other users reported that this worked for them in the past to fix arbitrary issues -- including another public one from the default list. Not sure which one you're using now. 

There's an open task for this project to replace the external Anisette server with an internal one running in a VM, but that's to be implemented and mainly to be tested due to the level of convolution this comes with for an android phone.

<br>

As for the records -- thanks. I think maybe it's keeping around naming information for tags that don't exist anymore (e.g. if you had an hold tag and you unlinked it and then linked it again?). Just a failure to clean them up. In which case you can basically for now ignore the error popup because all it will do when you get that popup is skip processing that tag.  

I'd be curious if you could confirm that by investigating the decoded contents of a full export (see [this doc](https://github.com/parawanderer/OpenTagViewer/blob/main/python/README.md#how-to-use) for that). Basically you should be able to recognise from the XML which tag of yours this probably used to be versus the other two. Not high priority, but would be a good curiosity to confirm the issue. For now I think I will just mute that error message and keep it as a log instead.

**Comment by SadGare** [comment]
After switching to another Anisette server several times, it finally works!!! Thank you for your patience in this issue and dedication to this wonderful repo. I will delve into the decoded contents later.

I would also like to give a little advice on enhancing the map API provider. The current service is based on Google Maps, which is great and works worldwide. However, in China, Google services are largely unavailable, making its maps inaccurate and outdated. Apple Maps in China, for example, chooses to cooperate with Amap (https://www.amap.com/
) as its data supplier. Could you consider adding an option to choose a different map data provider in the future, for users in regions where Google Maps is not readily available?

And again, the features you have implemented in this app are already splendid. Thank you for your effort.

**Comment by parawanderer** [comment]
I think, yeah, there's been some requests to add different map providers and I think that would be neat and in line with this app being part of the whole FOSS domain. The only reason I even went with Google here is that specifically on Android you get Google Maps "for free" (only platform where you do) and I'd used it before, so I defaulted to it. 

Maybe add your map provider suggestion here: https://github.com/parawanderer/OpenTagViewer/issues/16

I think the app will basically need some tweaking to make adding arbitrary map providers to it easier in the future, because right now a lot of logic in it is relatively tightly coupled to the Google map implementation (though probably relatively rewrite-able). 

Another issue is where to get the reverse-geocoding (coordinates to location name) information from. I get this from the Google Maps SDK right now but that's technically an external API.

**Comment by parawanderer** [comment]
Hi, this should now be [*mostly*](https://github.com/parawanderer/OpenTagViewer/issues/229) fixed as of [the new 1.1.0 release](https://github.com/parawanderer/OpenTagViewer/releases/tag/android-app-v1.1.0). Have a look, and feel free to open a new issue if you find more bugs.
